### ISSUE TITLE
Incomplete/corrupted download of Parity

### ISSUE THREAD

**Issue by axelchalon** [paritytech/fether#172]
Happened from the beginning.

Related: https://github.com/parity-js/shell/issues/119

![image](https://user-images.githubusercontent.com/5739676/43675754-6136b636-97e5-11e8-9708-7231fbf19f0a.png)

## Console 
```
[2018-08-04T10:51:43.199Z] INFO (@parity/electron:main/10491 on archon): Parity found on machine, can be run with "/home/xx/.config/Electron/parity".
[2018-08-04T10:51:50.258Z] INFO (@parity/electron:main/10491 on archon): Running "/home/xx/.config/Electron/parity --light --chain kovan --ws-interface 127.0.0.1 --ws-port 8546".
[2018-08-04T10:51:50.265Z] ERROR (fether/10491 on archon): Exit code null, with signal SIGSEGV.
    Error: Exit code null, with signal SIGSEGV.
        at ChildProcess.<anonymous> (/home/xx/web/parity-fether/packages/parity-electron/lib/runParity.js:110:39)
        at emitTwo (events.js:126:13)
        at ChildProcess.emit (events.js:214:7)
        at maybeClose (internal/child_process.js:925:16)
        at Socket.stream.socket.on (internal/child_process.js:346:11)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at Pipe._handle.close [as _onclose] (net.js:554:12)
```

## `fether.log`
```
{"level":30,"time":1533379903072,"msg":"Starting Fether...","pid":10491,"hostname":"archon","name":"fether","v":1}
{"level":30,"time":1533379903199,"msg":"Parity found on machine, can be run with \"/home/xx/.config/Electron/parity\".","pid":10491,"hostname":"archon","name":"@parity/electron:main","v":1}
{"level":30,"time":1533379910258,"msg":"Running \"/home/xx/.config/Electron/parity --light --chain kovan --ws-interface 127.0.0.1 --ws-port 8546\".","pid":10491,"hostname":"archon","name":"@parity/electron:main","v":1}
{"level":50,"time":1533379910265,"msg":"Exit code null, with signal SIGSEGV.","pid":10491,"hostname":"archon","name":"fether","type":"Error","stack":"Error: Exit code null, with signal SIGSEGV.\n    at ChildProcess.<anonymous> (/home/xx/web/parity-fether/packages/parity-electron/lib/runParity.js:110:39)\n    at emitTwo (events.js:126:13)\n    at ChildProcess.emit (events.js:214:7)\n    at maybeClose (internal/child_process.js:925:16)\n    at Socket.stream.socket.on (internal/child_process.js:346:11)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at Pipe._handle.close [as _onclose] (net.js:554:12)","v":1}
```

## Running downloaded Fether manually
```bash
$ /home/xx/.config/Electron/parity --light --chain kovan --ws-interface 127.0.0.1 --ws-port 8546
Segmentation fault

$ ls -lh /home/xx/.config/Electron/parity
-rwxr-xr-x 1 xx xx 252K Jul 13 16:38 /home/xx/.config/Electron/parity
```

252K... I guess the download failed?

Removing `/home/xx/.config/Electron/parity` and relaunching Fether (making it download Parity again) fixes the problem

**Comment by axelchalon** [comment]
Closing in favour of https://github.com/paritytech/fether/issues/173
