### ISSUE TITLE
Mac adds  -psn_0_2577013 to parity command at first launch

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#188]
Reported by @bjornwgnr 
Installed from GitHub dmg.

![image](https://user-images.githubusercontent.com/33178835/44723424-46a5f180-aad0-11e8-9081-424e8dc8ce6c.png)

Logs :
```
{"level":30,"time":1535224528045,"msg":"Starting Fether...","pid":11033,"hostname":"Bjorns-MacBook-Pro.local","name":"fether","v":1}
{"level":30,"time":1535224528164,"msg":"Parity found on machine, can be run with \"/Applications/Parity Ethereum.app/Contents/MacOS/parity\".","pid":11033,"hostname":"Bjorns-MacBook-Pro.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1535224535201,"msg":"Running \"/Applications/Parity\\ Ethereum.app/Contents/MacOS/parity -psn_0_2577013 --light --chain kovan --ws-interface 127.0.0.1 --ws-port 8546\".","pid":11033,"hostname":"Bjorns-MacBook-Pro.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1535224535259,"msg":"error: Found argument '-p' which wasn't expected, or isn't valid in this context\n\nUSAGE:\n    parity [SUBCOMMAND]\n\nFor more information try --help\n","pid":11033,"hostname":"Bjorns-MacBook-Pro.local","name":"@parity/parity","v":1}
{"level":50,"time":1535224535267,"msg":"Exit code 1, with signal null.","pid":11033,"hostname":"Bjorns-MacBook-Pro.local","name":"fether","type":"Error","stack":"Error: Exit code 1, with signal null.\n    at ChildProcess.<anonymous> (/Applications/Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/runParity.js:110:39)\n    at emitTwo (events.js:126:13)\n    at ChildProcess.emit (events.js:214:7)\n    at maybeClose (internal/child_process.js:925:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)","v":1}
```

**Comment by amaurymartiny** [comment]
@axelchalon Should we instead whitelist the list of arguments passed to parity? Using what you did with parity-config-generator.

**Comment by axelchalon** [comment]
hmm it feels like it's a bit overkill just to fix this issue, plus needs maintenance to update (regenerate) the list of whitelisted flags

This issue only seems to happen on old versions of Mac OS ?
https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder#comment86586356_10242200
https://apple.stackexchange.com/questions/207895/app-gets-in-commandline-parameter-psn-0-nnnnnn-why
> Pre to OSX 10.9 apps launced in GUI had a -psn parameter passed to them. [...] The methods are noted as removed in OS X 10.9

**Comment by amaurymartiny** [comment]
I think Bjorn's version was 10.13.4 (17E202) cf riot, the latest being 10.13.6.
