### ISSUE TITLE
AppImage does not run

### ISSUE THREAD

**Issue by probonopd** [paritytech/fether#222]
```
firejail ./BeingTested.AppImage zenity, kdialog, Xdialog missing. Skipping /run/firejail/appimage/.appimage-10027/AppRun.
module.js:545
    throw err;
    ^
Error: Cannot find module '/run/firejail/appimage/.appimage-10027/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
Parent pid 10027, child pid 10031
```

Related to electron-userland/electron-builder#2958? 

References:
* https://github.com/AppImage/appimage.github.io/pull/894
* https://travis-ci.org/AppImage/appimage.github.io/builds/448063972#L619-L630

**Comment by Tbaut** [comment]
Thanks for the issue. It was solved recently in https://github.com/paritytech/fether/issues/166 the new release will contain it.
