### ISSUE TITLE
Fether stuck in a connecting to node state

### ISSUE THREAD

**Issue by pepyakin** [paritytech/fether#240]
After I've just started a node the UI was showing "Connecting to node" for a long time. I waited for a few minutes and then looked into the logs which showed:

```

[2018-11-09T10:23:00.272Z] INFO (@parity/parity/17897 on pepyakin-macbook): 2018-11-09 11:23:00  Debug API is not available in light client mode.

[2018-11-09T10:23:00.274Z] INFO (@parity/parity/17897 on pepyakin-macbook): 2018-11-09 11:23:00  Debug API is not available in light client mode.

[2018-11-09T10:23:00.276Z] INFO (@parity/parity/17897 on pepyakin-macbook): 2018-11-09 11:23:00  Public node URL: enode://2aa7caf1d2eca1e9728390dd2f4469e98660a81d7c53ef27eac6236f5ebe370eff95260fd52fdd4f73b944d0af9fdcaf45564e43fb98a4708dcef7817f40fc8b@192.168.178.28:30303

[2018-11-09T10:23:01.710Z] ERROR (fether/17897 on pepyakin-macbook): Error extracting token.
    Error: Error extracting token.
        at Timeout._onTimeout (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/signerNewToken.js:78:32)
        at ontimeout (timers.js:475:11)
        at tryOnTimeout (timers.js:310:5)
        at Timer.listOnTimeout (timers.js:270:5)
[2018-11-09T10:23:02.174Z] INFO (@parity/parity/17897 on pepyakin-macbook): 2018-11-09 11:23:02  Imported #9023746 0x5668…5fec (0.00 Mgas)
and continued syncing
```

Apparently the client was syncing but UI was still displaying the "Connecting to node" state.

**Comment by axelchalon** [comment]
Did this happen during your first ever launch of Fether, and did everything go well when you relaunched Fether?

**Comment by axelchalon** [comment]
This should have been fixed with https://github.com/paritytech/js-libs/pull/26 ; we need to update `fether-electron`'s dependency to `@parity/electron`
