### ISSUE TITLE
Exit code 1 - "Failed to create lock file" when relaunching Fether too quickly

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#266]
This happened when launching Fether right after having closed it (happened on windows, reported to me, I could not reproduce on linux). 

It looks like Parity Ethereum did not have time to shutdown and release the lock on the DB when Fether launched the light client again, and it did not give it another chance.

![image](https://user-images.githubusercontent.com/33178835/48902897-452f5f80-ee5a-11e8-9d8b-0193c1d72588.png)

logs:
```
{"level":30,"time":1542883301680,"msg":"Starting Parity Fether...","pid":10544,"hostname":"DESKTOP-BHVEL1N","name":"fether","v":1}
{"level":30,"time":1542883301793,"msg":"Parity found on machine, can be run with \"C:\\Users\\Mattias\\AppData\\Roaming\\fether/parity.exe\".","pid":10544,"hostname":"DESKTOP-BHVEL1N","name":"@parity/electron:main","v":1}
{"level":30,"time":1542883302810,"msg":"Running \"C:\\Users\\Mattias\\AppData\\Roaming\\fether/parity.exe --light --chain kovan --ws-interface 127.0.0.1 --ws-port 8546\".","pid":10544,"hostname":"DESKTOP-BHVEL1N","name":"@parity/electron:main","v":1}
{"level":30,"time":1542883302890,"msg":"2018-11-22 21:41:42  Starting Parity-Ethereum/v2.2.1-beta-5c56fc502-20181114/x86_64-windows-msvc/rustc1.30.0\n2018-11-22 21:41:42  Keys path C:\\Users\\Mattias\\AppData\\Roaming\\Parity\\Ethereum\\keys\\kovan\n2018-11-22 21:41:42  DB path C:\\Users\\Mattias\\AppData\\Local\\Parity\\Ethereum\\chains_light\\kovan\\db\\9bf388941c25ea98\n","pid":10544,"hostname":"DESKTOP-BHVEL1N","name":"@parity/parity","v":1}
{"level":30,"time":1542883302891,"msg":"2018-11-22 21:41:42  Running in experimental Light Client mode.\n","pid":10544,"hostname":"DESKTOP-BHVEL1N","name":"@parity/parity","v":1}
{"level":30,"time":1542883302963,"msg":"Failed to open database Custom { kind: Other, error: StringError(\"IO error: Failed to create lock file: C:\\\\Users\\\\Mattias\\\\AppData\\\\Local\\\\Parity\\\\Ethereum\\\\chains_light\\\\kovan\\\\db\\\\9bf388941c25ea98\\\\overlayrecent\\\\db/LOCK: The process cannot access the file because it is being used by another process.\\r\\n\") }\n","pid":10544,"hostname":"DESKTOP-BHVEL1N","name":"@parity/parity","v":1}
{"level":50,"time":1542883302970,"msg":"Exit code 1, with signal null.","pid":10544,"hostname":"DESKTOP-BHVEL1N","name":"fether","type":"Error","stack":"Error: Exit code 1, with signal null.\n    at ChildProcess.<anonymous> (C:\\Users\\Mattias\\AppData\\Local\\Programs\\fether\\resources\\app.asar\\node_modules\\@parity\\electron\\lib\\runParity.js:148:43)\n    at emitTwo (events.js:126:13)\n    at ChildProcess.emit (events.js:214:7)\n    at maybeClose (internal/child_process.js:925:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)","v":1}
```

**Comment by Tbaut** [comment]
Closing as the issue is identified and Fether should ideally not be re-launched..
We can reopen if this happens too often and the use case makes sense.
