### ISSUE TITLE
Crash at Parity Download

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#277]
Just had a chat with a user on Mac that had the following crash log (on mac).

It seems that parity beta didn't have the expected checksum. Could very much be related to the upgrade we just had on Parity Ethereum.. This could be avoided with https://github.com/paritytech/fether/issues/204

```
{“level”:30,“time”:1543504092758,“msg”:“Starting Parity Fether…”,“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:“fether”,“v”:1}
{“level”:30,“time”:1543504093039,“msg”:“Parity not found on machine.”,“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:"@parity/electron:main",“v”:1}
{“level”:30,“time”:1543504093044,“msg”:“Downloading from https://vanity-service.parity.io/parity-binaries?version=beta&os=darwin&architecture=x86_64.",“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:"@parity/electron:main","v”:1}
{“level”:30,“time”:1543504112771,“msg”:“Retrying.”,“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:"@parity/electron:main",“v”:1}
{“level”:30,“time”:1543504112779,“msg”:“Downloading from https://vanity-service.parity.io/parity-binaries?version=beta&os=darwin&architecture=x86_64.",“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:"@parity/electron:main","v”:1}
{“level”:30,“time”:1543504125120,“msg”:“Retrying.”,“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:"@parity/electron:main",“v”:1}
{“level”:30,“time”:1543504125124,“msg”:“Downloading from https://vanity-service.parity.io/parity-binaries?version=beta&os=darwin&architecture=x86_64.",“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:"@parity/electron:main","v”:1}
{“level”:30,“time”:1543504133964,“msg”:“Retrying.”,“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:"@parity/electron:main",“v”:1}
{“level”:30,“time”:1543504133967,“msg”:“Downloading from https://vanity-service.parity.io/parity-binaries?version=beta&os=darwin&architecture=x86_64.",“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:"@parity/electron:main","v”:1}
{“level”:50,“time”:1543504140477,“msg”:“Checksum mismatch, expecting adc27b6f7ea7d66eb012a5c2a6036e304f09ebcf2f27b04d93731618c630d840, got 5bbdbf6d299de28b01cda672876dd7f7fcff540808db7678ef0ea4ed8ecee9f1.”,“pid”:49474,“hostname”:“Chriss-MacBook-Pro-4.local”,“name”:“fether”,“type”:“Error”,“stack”:“Error: Checksum mismatch, expecting adc27b6f7ea7d66eb012a5c2a6036e304f09ebcf2f27b04d93731618c630d840, got 5bbdbf6d299de28b01cda672876dd7f7fcff540808db7678ef0ea4ed8ecee9f1.\n at /Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:215:47\n at step (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:47:23)\n at Object.next (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:28:53)\n at fulfilled (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:19:58)\n at <anonymous>\n at process._tickCallback (internal/process/next_tick.js:188:7)”,“v”:1}
```

**Comment by Tbaut** [comment]
I can confirm, vanity is not up to date.
![image](https://user-images.githubusercontent.com/33178835/49233882-3f57f200-f3f7-11e8-86ef-5232da77c824.png)
```
sha256sum ~/Downloads/parity
5bbdbf6d299de28b01cda672876dd7f7fcff540808db7678ef0ea4ed8ecee9f1
```
