### ISSUE TITLE
Download Error on startup / Win10 x64

### ISSUE THREAD

**Issue by MoltenB** [paritytech/fether#278]
Can't launch Fether. This happens when not running a parity light node in the background, and also when 
 I do have one running.

The client opens to the 'Connecting to the node...' page then gives me this message in rapid succession: `Download Error
The download of parity.exe was interrupted`

After closing this dialogue box a few times I get the following error:
`An error occured.

OS: win32
Arch: x64
Channel: beta
Error: The download of parity.exe was interrupted`

Log file - I removed hostname and user name from this:
`{"level":30,"time":1544101844900,"msg":"Starting Parity Fether...","pid":11044,"hostname":"***","name":"fether","v":1}
{"level":30,"time":1544101845043,"msg":"Parity not found on machine.","pid":11044,"hostname":"***","name":"@parity/electron:main","v":1}
{"level":30,"time":1544101845048,"msg":"Downloading from https://vanity-service.parity.io/parity-binaries?version=beta&os=windows&architecture=x86_64.","pid":11044,"hostname":"***","name":"@parity/electron:main","v":1}
{"level":30,"time":1544102165476,"msg":"Retrying.","pid":11044,"hostname":"***","name":"@parity/electron:main","v":1}
{"level":30,"time":1544102165478,"msg":"Downloading from https://vanity-service.parity.io/parity-binaries?version=beta&os=windows&architecture=x86_64.","pid":11044,"hostname":"***","name":"@parity/electron:main","v":1}
{"level":30,"time":1544102169049,"msg":"Retrying.","pid":11044,"hostname":"***","name":"@parity/electron:main","v":1}
{"level":30,"time":1544102169051,"msg":"Downloading from https://vanity-service.parity.io/parity-binaries?version=beta&os=windows&architecture=x86_64.","pid":11044,"hostname":"***","name":"@parity/electron:main","v":1}
{"level":30,"time":1544102200389,"msg":"Retrying.","pid":11044,"hostname":"***","name":"@parity/electron:main","v":1}
{"level":30,"time":1544102200391,"msg":"Downloading from https://vanity-service.parity.io/parity-binaries?version=beta&os=windows&architecture=x86_64.","pid":11044,"hostname":"***","name":"@parity/electron:main","v":1}
{"level":50,"time":1544102201827,"msg":"The download of parity.exe was interrupted","pid":11044,"hostname":"***","name":"fether","type":"Error","stack":"Error: The download of parity.exe was interrupted\n    at DownloadItem.item.on (C:\\Users\\***\\AppData\\Local\\Programs\\fether\\resources\\app.asar\\node_modules\\electron-dl\\index.js:109:8)\n    at emitTwo (events.js:126:13)\n    at DownloadItem.emit (events.js:214:7)","v":1}
`

**Comment by axelchalon** [comment]
Hi, thanks for reporting. I can reproduce. We're working on a fix right now.

In the meantime, you can add the Parity binary to your $PATH; the bug shouldn't happen then.
