### ISSUE TITLE
Unable to run tests on macOS

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#300]
I tried to run the unit tests for Fether with `yarn; yarn run build; yarn run test`, but it gives the error shown below. I'm using macOS 10.14. I switched to Node.js v10.14.2. I'm using Yarn version 1.12.3.

```
scon @ ~/code/src/paritytech/fether - [master] $ nvm use v10.14.2
Now using node v10.14.2 (npm v6.4.1)
scon @ ~/code/src/paritytech/fether - [master] $ yarn; yarn run build; yarn run test
yarn install v1.12.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.23s.
yarn run v1.12.3
$ lerna run build
lerna info version 2.11.0
$ rimraf lib
$ babel src --out-dir lib
🎉  Successfully compiled 35 files with Babel.
$ npm-run-all build-*
$ node-sass-chokidar src/ -o src/
$ react-app-rewired build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  400.53 KB (-37 B)  build/static/js/main.d6d9ed42.js
  45.51 KB           build/static/js/1.69905f60.chunk.js
  16.71 KB           build/static/js/0.2d7b1594.chunk.js
  7.04 KB            build/static/css/main.085abab8.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  http://bit.ly/2vY88Kr

$ copyfiles -u 2 "../fether-react/build/**/*" static/ && ./scripts/fixElectronBug.sh
$ electron-webpack
Hash: 7d4827e6b84c097663d4
Version: webpack 4.12.1
Child
    Hash: 7d4827e6b84c097663d4
    Time: 1390ms
    Built at: 12/15/2018 1:15:37 AM
          Asset      Size  Chunks             Chunk Names
        main.js   8.3 KiB       0  [emitted]  main
    main.js.map  9.65 KiB       0  [emitted]  main
     [0] external "electron" 42 bytes {0} [built]
     [1] external "@parity/electron" 42 bytes {0} [built]
     [2] ./package.json 1.56 KiB {0} [built]
     [3] external "fs" 42 bytes {0} [built]
     [4] ./electron-builder.json 346 bytes {0} [built]
     [5] external "pino" 42 bytes {0} [built]
     [6] external "commander" 42 bytes {0} [built]
     [7] external "pino-multi-stream" 42 bytes {0} [built]
     [8] external "url" 42 bytes {0} [built]
     [9] external "path" 42 bytes {0} [built]
    [10] external "commander-remaining-args" 42 bytes {0} [built]
    [11] ./src/main/index.js + 6 modules 11.9 KiB {0} [built]
         | ./src/main/index.js 4.05 KiB [built]
         | ./src/main/menu/index.js 2.09 KiB [built]
         | ./src/main/cli/index.js 1.54 KiB [built]
         | ./src/main/utils/pino.js 1.55 KiB [built]
         | ./src/main/utils/handleError.js 1.03 KiB [built]
         | ./src/main/messages/index.js 1.13 KiB [built]
         | ./src/main/utils/staticPath.js 434 bytes [built]
    [12] multi ./src/main/index.js 28 bytes {0} [built]
lerna success run Ran npm script 'build' in packages:
lerna success - fether
lerna success - fether-react
lerna success - fether-ui
✨  Done in 57.55s.
yarn run v1.12.3
$ semistandard '**/*.{js,ts}' --parser babel-eslint && CI=true lerna run test --parallel
lerna info version 2.11.0
lerna info run in 2 package(s): npm run test
fether: $ echo Skipped.
fether-react: $ react-app-rewired test --env=jsdom
fether: Skipped.
fether-react: /Users/scon/code/src/paritytech/fether/node_modules/react-scripts/scripts/test.js:20\n  throw err;\n  ^
fether-react: Error: No available storage method found.\n    at /Users/scon/code/src/paritytech/fether/node_modules/localforage/dist/localforage.js:2743:25\n    at process._tickCallback (internal/process/next_tick.js:68:7)
fether-react: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
fether-react: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run test
lerna ERR! /Users/scon/code/src/paritytech/fether/node_modules/react-scripts/scripts/test.js:20
lerna ERR!   throw err;
lerna ERR!   ^
lerna ERR! 
lerna ERR! Error: No available storage method found.
lerna ERR!     at /Users/scon/code/src/paritytech/fether/node_modules/localforage/dist/localforage.js:2743:25
lerna ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
lerna ERR! error Command failed with exit code 1.
lerna ERR! 
lerna ERR! $ react-app-rewired test --env=jsdom
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/scon/code/src/paritytech/fether/node_modules/lerna/node_modules/execa/index.js:236:11)
{ Error: Command failed: yarn run test
/Users/scon/code/src/paritytech/fether/node_modules/react-scripts/scripts/test.js:20
  throw err;
  ^

Error: No available storage method found.
    at /Users/scon/code/src/paritytech/fether/node_modules/localforage/dist/localforage.js:2743:25
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.

$ react-app-rewired test --env=jsdom
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/scon/code/src/paritytech/fether/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
   '$ react-app-rewired test --env=jsdom\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr:
   '/Users/scon/code/src/paritytech/fether/node_modules/react-scripts/scripts/test.js:20\n  throw err;\n  ^\n\nError: No available storage method found.\n    at /Users/scon/code/src/paritytech/fether/node_modules/localforage/dist/localforage.js:2743:25\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nerror Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run test',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ltfschoen** [comment]
it's working now, although i'm not sure what was originally wrong
