### ISSUE TITLE
Unable to run on Windows 7 32-bit

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#378]
I tried running the latest 'master' branch of Fether from a Windows 7 32-bit VM using Virtual Box
In the VM I installed Git 2.20.1.windows.1, Yarn 1.13.0, and Node.js 11.7.0, and then ran `yarn; yarn start`

But it displays a blank screen and the following error:

<img width="965" alt="screen shot 2019-01-20 at 9 58 07 pm" src="https://user-images.githubusercontent.com/6226175/51438297-a363ac00-1cfe-11e9-8a98-db0d7036d756.png">

The fether.log contents is:

```
{"level":30,"time":1547981795342,"msg":"Starting Parity Fether...","pid":6128,"hostname":"IEWIN7","name":"fether","v":1}
{"level":30,"time":1547981795569,"msg":"Parity found on machine, can be run with \"C:\\Users\\IEUser\\AppData\\Roaming\\Electron/parity.exe\".","pid":6128,"hostname":"IEWIN7","name":"@parity/electron:main","v":1}
{"level":50,"time":1547981796579,"msg":"spawn UNKNOWN","pid":6128,"hostname":"IEWIN7","name":"fether","type":"Error","stack":"Error: spawn UNKNOWN\n    at _errnoException (util.js:1024:11)\n    at ChildProcess.spawn (internal/child_process.js:323:11)\n    at Object.exports.spawn (child_process.js:514:9)\n    at C:\\Users\\IEUser\\code\\fether\\node_modules\\@parity\\electron\\lib\\runParity.js:112:50\n    at new Promise (<anonymous>)\n    at C:\\Users\\IEUser\\code\\fether\\node_modules\\@parity\\electron\\lib\\runParity.js:109:47\n    at step (C:\\Users\\IEUser\\code\\fether\\node_modules\\@parity\\electron\\lib\\runParity.js:47:23)\n    at Object.next (C:\\Users\\IEUser\\code\\fether\\node_modules\\@parity\\electron\\lib\\runParity.js:28:53)\n    at fulfilled (C:\\Users\\IEUser\\code\\fether\\node_modules\\@parity\\electron\\lib\\runParity.js:19:58)\n    at <anonymous>","code":"UNKNOWN","errno":"UNKNOWN","syscall":"spawn","v":1}
```

**Comment by ltfschoen** [comment]
I just tried to download a 32-bit (x86) release of Parity Ethereum, but none exists.
I'll have to find an image of a 64-bit (x64) Windows version.

**Comment by ltfschoen** [comment]
It works on Windows 10 64-bit.

I downloaded the Windows 10 64-bit evaluation from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/.
I imported the downloaded OVF using into Virtual Box from File > Import Appliance
I further configured the VMs settings in Virtual Box with:
* General > Advanced > Shared Clipboard > Bidirectional
* General > Advanced > Drag'n'Drop > Bidirectional
* System > Motherboard > 2Gb base memory
* System > Processor > 2 CPUs
* Display > Screen > 150 MB Video Memory
* Display > Screen > Scale Factor 150%
* Display > Screen > Graphics Controller > VBoxSVGA + Enable 3D Acceleration
* Shared Folders > Added /Users/me/Public 

After running the VM. I installed:
* Git Windows
* Yarn for Windows
* Node.js for Windows
* Python 3 for Windows
* Restart the VM Restart terminal

Then I ran Git Bash (from Git Windows) and:
* Cloned and ran Fether

<img width="766" alt="screen shot 2019-01-21 at 6 24 51 pm" src="https://user-images.githubusercontent.com/6226175/51458631-f8103100-1da9-11e9-8747-2cac8b87ccef.png">
