### ISSUE TITLE
Fether unable to find or connect with Parity on Mac OS X

### ISSUE THREAD

**Issue by pkeithhynes** [paritytech/fether#426]
iMac Retina 5K, 27-inch, Late 2015
macOS Mojave Version 10.14
32 GB RAM
3.12 TB disk

parity  version Parity-Ethereum/v2.2.10-stable-7b1d3e180-20190213/x86_64-macos/rustc1.32.0
fether 0.2.0

I have tried running parity and fether together in two ways:
1) By independently starting Parity and Fether
2) By using Fether to start Parity.
I get a similar failure in each case.

Patricks-iMac:~ pkh$ /Applications/'Parity Fether.app'/Contents/MacOs/'Parity Fether' --chain ropsten --light
[2019-02-14T03:56:22.914Z] INFO (fether/3321 on Patricks-iMac.local): Starting Parity Fether...
GVA info: Successfully connected to the Intel plugin, offline Gen9 
[2019-02-14T03:56:22.991Z] INFO (@parity/electron:main/3321 on Patricks-iMac.local): Parity not found on machine.
[2019-02-14T03:56:22.997Z] INFO (@parity/electron:main/3321 on Patricks-iMac.local): Downloading from https://vanity-service.parity.io/parity-binaries?version=stable&os=darwin&architecture=x86_64.
[2019-02-14T03:56:28.739Z] INFO (@parity/electron:main/3321 on Patricks-iMac.local): Retrying.
[2019-02-14T03:56:28.741Z] INFO (@parity/electron:main/3321 on Patricks-iMac.local): Downloading from https://vanity-service.parity.io/parity-binaries?version=stable&os=darwin&architecture=x86_64.
[2019-02-14T03:56:35.082Z] INFO (@parity/electron:main/3321 on Patricks-iMac.local): Retrying.
[2019-02-14T03:56:35.085Z] INFO (@parity/electron:main/3321 on Patricks-iMac.local): Downloading from https://vanity-service.parity.io/parity-binaries?version=stable&os=darwin&architecture=x86_64.
[2019-02-14T03:56:43.414Z] INFO (@parity/electron:main/3321 on Patricks-iMac.local): Retrying.
[2019-02-14T03:56:43.416Z] INFO (@parity/electron:main/3321 on Patricks-iMac.local): Downloading from https://vanity-service.parity.io/parity-binaries?version=stable&os=darwin&architecture=x86_64.
[2019-02-14T03:56:47.787Z] ERROR (fether/3321 on Patricks-iMac.local): Checksum mismatch, expecting 1690ea47227e45b3b67256734e3020a958c9a4b6c458fa21bbda2f55d91819ed, got ca623463357e91611cf4ae31cc911dc59a5ba1f84d63155a6e0f4b6922435d5d.
    Error: Checksum mismatch, expecting 1690ea47227e45b3b67256734e3020a958c9a4b6c458fa21bbda2f55d91819ed, got ca623463357e91611cf4ae31cc911dc59a5ba1f84d63155a6e0f4b6922435d5d.
        at /Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:215:47
        at step (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:47:23)
        at Object.next (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:28:53)
        at fulfilled (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:19:58)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

The log file contains the following:
{"level":30,"time":1550116582914,"msg":"Starting Parity Fether...","pid":3321,"hostname":"Patricks-iMac.local","name":"fether","v":1}
{"level":30,"time":1550116582991,"msg":"Parity not found on machine.","pid":3321,"hostname":"Patricks-iMac.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1550116582997,"msg":"Downloading from https://vanity-service.parity.io/parity-binaries?version=stable&os=darwin&architecture=x86_64.","pid":3321,"hostname":"Patricks-iMac.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1550116588739,"msg":"Retrying.","pid":3321,"hostname":"Patricks-iMac.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1550116588741,"msg":"Downloading from https://vanity-service.parity.io/parity-binaries?version=stable&os=darwin&architecture=x86_64.","pid":3321,"hostname":"Patricks-iMac.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1550116595082,"msg":"Retrying.","pid":3321,"hostname":"Patricks-iMac.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1550116595085,"msg":"Downloading from https://vanity-service.parity.io/parity-binaries?version=stable&os=darwin&architecture=x86_64.","pid":3321,"hostname":"Patricks-iMac.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1550116603414,"msg":"Retrying.","pid":3321,"hostname":"Patricks-iMac.local","name":"@parity/electron:main","v":1}
{"level":30,"time":1550116603416,"msg":"Downloading from https://vanity-service.parity.io/parity-binaries?version=stable&os=darwin&architecture=x86_64.","pid":3321,"hostname":"Patricks-iMac.local","name":"@parity/electron:main","v":1}
{"level":50,"time":1550116607787,"msg":"Checksum mismatch, expecting 1690ea47227e45b3b67256734e3020a958c9a4b6c458fa21bbda2f55d91819ed, got ca623463357e91611cf4ae31cc911dc59a5ba1f84d63155a6e0f4b6922435d5d.","pid":3321,"hostname":"Patricks-iMac.local","name":"fether","type":"Error","stack":"Error: Checksum mismatch, expecting 1690ea47227e45b3b67256734e3020a958c9a4b6c458fa21bbda2f55d91819ed, got ca623463357e91611cf4ae31cc911dc59a5ba1f84d63155a6e0f4b6922435d5d.\n    at /Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:215:47\n    at step (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:47:23)\n    at Object.next (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:28:53)\n    at fulfilled (/Applications/Parity Fether.app/Contents/Resources/app.asar/node_modules/@parity/electron/lib/fetchParity.js:19:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","v":1}

**Comment by yjkimjunior** [comment]
@pkeithhynes I couldn't reproduce. Could you make sure you're on the latest release for both please?

Fether: https://github.com/paritytech/fether/releases/tag/v0.2.0-beta
Parity-Ethereum: https://github.com/paritytech/parity-ethereum/releases/tag/v2.3.3

**Comment by pkeithhynes** [comment]
I loaded Parity-Ethereum 2.3.3 using Home-brew from the link above
Fether is at 0.2.0 beta.

Unfortunately I am having the same issue - Fether is not seeing Parity data whether I launch Parity separately or use Fether to try to launch it.

I assume I have messed up my configuration somehow....any ideas?

**Comment by pkeithhynes** [comment]
Problem resolved by starting parity in a terminal window and starting fether using the OSX dock icon.

**Comment by yjkimjunior** [comment]
@pkeithhynes cool, but are you still having the original issues? Are you able to get synced running just Fether?

**Comment by Tbaut** [comment]
closing as stale
