### ISSUE TITLE
Error in fetch-latest-parity.js script on Windows

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#480]
When running `yarn electron` in the latest `luke-124-security` branch, it's giving me the following error associated with the fetch-latest-parity.js script

<img width="420" alt="Screen Shot 2019-03-30 at 6 09 22 pm" src="https://user-images.githubusercontent.com/6226175/55279273-1dc03600-5317-11e9-808d-f9609d7d3d6e.png">

**Comment by Tbaut** [comment]
It looks like there is a `/` too much. In the cmd.
Probably related, I also couldn't launch fether after a fresh install on windows:

`C:\Users\Win10\AppData\Local\Programs\fether\resources\static\parity.exe ENOENT`

In this directory I have `parity` but no `parity.exe`. Renaming doesn't solve the problem, the file isn't recognized as an executable.

Full log
```
 [2019-03-31T13:58:41.959Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Platform detected:  win32
[2019-03-31T13:58:41.980Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Creating window
[2019-03-31T13:58:42.005Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Finished configuring Electron menu
[2019-03-31T13:58:42.012Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Finished creating window
[2019-03-31T13:58:42.026Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Configuring taskbar mode for the window
[2019-03-31T13:58:42.026Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Showing Tray Balloon
[2019-03-31T13:58:42.036Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Showing window id:  1
[2019-03-31T13:58:42.036Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Showing window
[2019-03-31T13:58:42.038Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Calculated window position:  {"x":2165,"y":885}
[2019-03-31T13:58:42.041Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Previously saved window position exists:  true
[2019-03-31T13:58:42.043Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Loaded window position:  {"x":2165,"y":885}
[2019-03-31T13:58:42.043Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Fixed window position:  {}
[2019-03-31T13:58:42.052Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Fether window resized. Moving it back up into view if required
[2019-03-31T13:58:42.053Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Window resolution (previous, current):  undefined {"x":2560,"y":1440}
[2019-03-31T13:58:42.059Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Saved window position after move (x: 2165, y: 885)
[2019-03-31T13:58:42.060Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Finished showing window
[2019-03-31T13:58:42.061Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Ready to use Parity Fether
[2019-03-31T13:58:43.039Z] INFO (@parity/electron:main/9932 on DESKTOP-DPKCKJ6): Running "C:\Users\Win10\AppData\Local\Programs\fether\resources\static\parity.exe --light --light --chain kovan --ws-interface 127.0.0.1 --ws-port 8546".
[2019-03-31T13:58:43.040Z] ERROR (fether/9932 on DESKTOP-DPKCKJ6): spawn C:\Users\Win10\AppData\Local\Programs\fether\resources\static\parity.exe ENOENT
    Error: spawn C:\Users\Win10\AppData\Local\Programs\fether\resources\static\parity.exe ENOENT
        at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
        at onErrorNT (internal/child_process.js:407:16)
        at process._tickCallback (internal/process/next_tick.js:63:19)
[2019-03-31T13:58:43.044Z] ERROR (fether/9932 on DESKTOP-DPKCKJ6): Exit code -4058, with signal null.
    Error: Exit code -4058, with signal null.
        at ChildProcess.<anonymous> (C:\Users\Win10\AppData\Local\Programs\fether\resources\app.asar\node_modules\@parity\electron\lib\runParity.js:153:43)
        at ChildProcess.emit (events.js:182:13)
        at maybeClose (internal/child_process.js:962:16)
        at Socket.stream.socket.on (internal/child_process.js:381:11)
        at Socket.emit (events.js:182:13)
        at Pipe._handle.close (net.js:606:12)
[2019-03-31T13:58:43.068Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Blur window
[2019-03-31T13:58:46.844Z] INFO (fether/9932 on DESKTOP-DPKCKJ6): Leaving Fether
```

**Comment by Tbaut** [comment]
I could build successfully a working windows version by removing the last `/` here https://github.com/paritytech/fether/blob/489e5383aa5a2055c652e86e14d3d8b330579ac7/scripts/fetch-latest-parity.js#L34

**Comment by ltfschoen** [comment]
> I could build successfully a working windows version by removing the last `/` here
> 
> [fether/scripts/fetch-latest-parity.js](https://github.com/paritytech/fether/blob/489e5383aa5a2055c652e86e14d3d8b330579ac7/scripts/fetch-latest-parity.js#L34)
> 
> Line 34 in [489e538](/paritytech/fether/commit/489e5383aa5a2055c652e86e14d3d8b330579ac7)
> 
>  const STATIC_DIRECTORY = '../packages/fether-electron/static/';

Cool, I thought I tried doing that too using Windows 10 in VM but I still got the error I mentioned. I'll try again to double check.

**Comment by ltfschoen** [comment]
I can build it too after removing the `/` that you mentioned, but during the build process it still shows that error. It also shows a separate scrypt error, which appears to be because its trying to use the Python 3 binary to run a `print` command but it's using the old Python 2 syntax. See screenshot below:

<img width="488" alt="Screen Shot 2019-03-31 at 8 21 47 pm" src="https://user-images.githubusercontent.com/6226175/55293101-baa3d180-53f2-11e9-8293-c1240d3fb9e2.png">

**Comment by axelchalon** [comment]
well, looks like we need to use `path.join` instead of concatenating the folders manually, so that it uses backslashes on windows. apparently forward slashes on windows have a special meaning https://stackoverflow.com/a/54460403
