### ISSUE TITLE
./fether-0.3.1-x86_64.AppImage  --> The SUID sandbox helper binary was found, but is not configured correctly

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/fether#573]
```
./fether-0.3.1-x86_64.AppImage 

[16582:1104/224942.596600:FATAL:setuid_sandbox_host.cc(157)] 
The SUID sandbox helper binary was found, but is not configured correctly. 
Rather than run without sandboxing I'm aborting now. 
You need to make sure that /tmp/.mount_fetherrg9M1e/chrome-sandbox 
is owned by root and has mode 4755.
Trace/breakpoint trap

ls -la
...
-rwxr--r--  1 username username 136628348 Nov  4 20:36 fether-0.3.1-x86_64.AppImage

ls -la / | grep tmp
drwxrwxrwt  17 root root     36864 Nov  4 22:46 tmp
```

**Comment by drandreaskrueger** [comment]
```
uname -a
Linux ... 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux
```

**Comment by drandreaskrueger** [comment]
Hah, this helped:

```
./fether-0.3.1-x86_64.AppImage --no-sandbox
```
Initially it still caused an error ... but then not anymore when I had started `parity --light` before.

Now the next issue ... isn't there a way to RESIZE that window?

**Comment by drandreaskrueger** [comment]
while this workaround for v0.3.1

    ./fether-0.3.1-x86_64.AppImage_ALT --no-sandbox

worked ... it doesn't anymore for v0.4.2:

```
./Parity-Fether-0.4.2.AppImage --no-sandbox
i18next: languageChanged en
i18next: initialized {
  debug: true,
...}
error: unknown option `--no-sandbox'
```

any hints? Thanks.

**Comment by drandreaskrueger** [comment]
tried another way (avoiding the possibly malformed AppImage):

```
sudo gdebi fether_0.4.2_amd64.deb
which fether 
/usr/bin/fether

/usr/bin/fether
[19983:1214/231357.132712:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Parity Fether/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

ls /opt/Parity\ Fether/chrome-sandbox -la
-rwxr-xr-x 1 root root 5568648 Dec  5 18:14 '/opt/Parity Fether/chrome-sandbox'

sudo chmod 4755 /opt/Parity\ Fether/chrome-sandbox
ls /opt/Parity\ Fether/chrome-sandbox -la
-rwsr-xr-x 1 root root 5568648 Dec  5 18:14 '/opt/Parity Fether/chrome-sandbox'
```
one error less, but still:
```
/usr/bin/fether
Trace/breakpoint trap
```

the new version 0.4.2 has made it worse over version 0.3.1 because this CLI switch stopped working: https://github.com/paritytech/fether/issues/573#issuecomment-549639255

**Comment by drandreaskrueger** [comment]
Now I have also tried to build it from source:

```
yarn electron

yarn run v1.21.1
...
Compiled successfully.
...
lerna success - fether-ui
$ cd packages/fether-electron && yarn electron
$ electron dist/main/main.js
[23263:1214/232856.924210:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that ~/paritytech_fether/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
Done in 94.17s.
```

and

```
yarn package

yarn run v1.21.1
$ yarn build
$ lerna run build
lerna notice cli v3.18.3
...
    make: *** [scrypt.target.mk:129: Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
    gyp ERR! System Linux 4.19.0-6-amd64
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd ~/paritytech_fether/node_modules/scrypt
    gyp ERR! node -v v11.15.0
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok 
    error Command failed with exit code 1.
...  
                                             command=/usr/local/bin/node /usr/share/yarn/bin/yarn.js run install
...
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=5.548s
Done in 431.80s.
```
and
```
yarn start
yarn run v1.21.1
$ npm-run-all -l -p start-*
[start-ui      ] $ cd packages/fether-ui && yarn start
[start-react   ] $ cd packages/fether-react && yarn start
[start-electron] $ cd packages/fether-electron && yarn start
[start-ui      ] $ yarn build --watch
[start-react   ] $ npm-run-all -p start-*
[start-electron] $ cross-env ELECTRON_START_URL=http://localhost:3000 electron-webpack dev
[start-ui      ] $ rimraf lib
[start-ui      ] $ babel src --out-dir lib --watch
[start-react   ] $ cross-env SKIP_PREFLIGHT_CHECK=true BROWSER=none craco start
[start-react   ] $ npm run build-css -- --watch --recursive
[start-react   ] npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1576363037220-0.025135679905072372/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[start-react   ] 
[start-react   ] > fether-react@0.4.2 build-css ~/paritytech_fether/packages/fether-react
[start-react   ] > node-sass-chokidar src/ -o src/ "--watch" "--recursive"
[start-react   ] 
[start-react   ] => changed: ~/paritytech_fether/packages/fether-react/src/index.sass
[start-react   ] Rendering Complete, saving .css file...
[start-react   ] Wrote CSS to ~/paritytech_fether/packages/fether-react/src/index.css
[start-ui      ] Successfully compiled 45 files with Babel.
[start-electron] ┏ Main -----------------------
[start-electron] 
[start-electron]   Hash: fc83738cd5d1b3f8b46d
[start-electron]   Version: webpack 4.41.2
[start-electron]   Time: 1824ms
[start-electron]   Built at: 12/14/2019 11:37:20 PM
[start-electron]     Asset     Size  Chunks             Chunk Names
[start-electron]   main.js  438 KiB    main  [emitted]  main
[start-electron]   Entrypoint main = main.js
[start-electron]   [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {main} [built]
[start-electron]   [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] 582 bytes {main} [built]
[start-electron]   [./package.json] 1.74 KiB {main} [built]
[start-electron]   [./src/main/app/index.js] 4.48 KiB {main} [built]
[start-electron]   [./src/main/app/methods/index.js] 1.74 KiB {main} [built]
[start-electron]   [./src/main/app/options/config/index.js] 6.2 KiB {main} [built]
[start-electron]   [./src/main/app/options/index.js] 379 bytes {main} [built]
[start-electron]   [./src/main/app/utils/isTrustedNavigationUrl.js] 739 bytes {main} [built]
[start-electron]   [./src/main/app/utils/pino.js] 993 bytes {main} [built]
[start-electron]   [./src/main/index.js] 4.31 KiB {main} [built]
[start-electron]   [@parity/electron] external "@parity/electron" 42 bytes {main} [built]
[start-electron]   [electron] external "electron" 42 bytes {main} [built]
[start-electron]   [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {main} [built]
[start-electron]   [source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {main} [built]
[start-electron]   [url] external "url" 42 bytes {main} [built]
[start-electron]       + 69 hidden modules
[start-electron] 
[start-electron] ┗ ----------------------------
[start-react   ] Starting the development server...
[start-react   ] 
[start-electron] ┏ Electron -------------------
[start-electron] 
[start-electron]   [25774:1214/233721.221857:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that ~/paritytech_fether/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
[start-electron] 
[start-electron] ┗ ----------------------------
[start-react   ] Compiled successfully!
[start-react   ] 
[start-react   ] You can now view fether-react in the browser.
[start-react   ] 
[start-react   ]   Local:            http://localhost:3000/
[start-react   ]   On Your Network:  http://192.168.178.51:3000/
[start-react   ] 
[start-react   ] Note that the development build is not optimized.
[start-react   ] To create a production build, use npm run build.
[start-react   ] 

```

then when I open http://localhost:3000/ I have to accept the T&C ... and then ...

the page is WHITE. Nothing.

**Comment by drandreaskrueger** [comment]
Alright, giving up, going back to my workaround:

    ./fether-0.3.1-x86_64.AppImage --no-sandbox

Questions: (a) is there any known security issue with that version 0.3.1, or am I save when I continue to use that ? or: (b) which newer fether version would also still work with that switch `--no-sandbox`? and (c) do you have any idea what could cause this problem, and how to fix it, for a version 0.4.3 ? 

Thanks a lot.

**Comment by drandreaskrueger** [comment]
Tried with the newest version, same error:

```
./Parity-Fether-0.4.3.AppImage
[13517:0220/221659.113271:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Parity8byHJA/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```
and it doesn't understand `--no-sandbox`

```
./Parity-Fether-0.4.3.AppImage --no-sandbox
i18next: languageChanged en
i18next: initialized {
  debug: true,
  initImmediate: true,
  ns: [ 'fether' ],
  defaultNS: 'fether',
  fallbackLng: [ 'en-US', 'en', 'de-DE', 'de' ],
  fallbackNS: false,
  whitelist: false,
  nonExplicitWhitelist: false,
  load: 'all',
  preload: false,
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  partialBundledLanguages: false,
  saveMissing: true,
  updateMissing: false,
  saveMissingTo: 'fallback',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: [Function: returnedObjectHandler],
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: handle],
  interpolation: { escapeValue: false },
  lng: 'en',
  resources: { en: { fether: [Object] }, de: { fether: [Object] } }
}
error: unknown option `--no-sandbox'
```



Debian Linux.

**Comment by drandreaskrueger** [comment]
Using this instead:

https://download.mycrypto.com/   
./linux-x86-64_1.7.7_MyCrypto.AppImage
